### ISSUE TITLE
AUR release?

### ISSUE THREAD

**Issue by silentnoodlemaster** [AbdelrhmanNile/steal#23]
the legalities might be an issue, but you are hosting this on github so does not seem that serious

**Comment by AbdelrhmanNile** [comment]
if someone would like to maintain an AUR package then they are welcome :)

**Comment by silentnoodlemaster** [comment]
could you share your PKGBUILD file?

**Comment by AbdelrhmanNile** [comment]
i uploaded the PKGBUILD and post.install now:)

**Comment by silentnoodlemaster** [comment]
decided to take a slightly different approach

**Comment by AbdelrhmanNile** [comment]
hi, thank you for maintaining the AUR package for steal :)
steal had an update yesterday removing the "steal.kv" file and now your package isnt building, please consider updating it
thank you !

**Comment by AbdelrhmanNile** [comment]
@silentnoodlemaster also i noticed the dependencies are missing zpaq

**Comment by silentnoodlemaster** [comment]
updated
