### ISSUE TITLE
Flatpack version?

### ISSUE THREAD

**Issue by khalilgharbaoui** [AbdelrhmanNile/steal#31]
Please add flatpack or appimage or snap verison or dockerized version of this?

**Comment by AbdelrhmanNile** [comment]
if anyone is willing to maintain it i have no problem

**Comment by AbdelrhmanNile** [comment]
i think it will be hard to do so since steal is not a binary  because its hard and annoying to package a python kivy app for for linux
i am thinking about re writing steal with flutter, then i might consider shipping it as an appimage

**Comment by khalilgharbaoui** [comment]
Or make it web based, so people can simply go to 127.0.0.1:3000

**Comment by GarnetSunset** [comment]
I would love if this became a thing so steam decks could be all in one :)

**Comment by khalilgharbaoui** [comment]
@GarnetSunset I actually got this working on steam deck with a lot of workarounds 😅

**Comment by GarnetSunset** [comment]
Yo yo yo can you document how? Does it involve disabling read only?

**Comment by khalilgharbaoui** [comment]
> Yo yo yo can you document how? Does it involve disabling read only?

Yes it needs to be disabled and after installing all needed dependencies enabled again otherwise any new updates will remove all and you would have to start over.

sofar i can see the index with all images and can initiate a download.

within each finished download there is a script
I kind of grabbed some lines out that and ran them seperatly in the terminal to unpack. after unpacking just added the main .exe to steam or lutris and using proton or the usual.

running them with the script directly wont work.

it's a lengthy proccess with too many steps to document to be honest. I could show you if you PM me: cbk0spvab@mozmail.com

otherwise I might document it at some point if i find the time.

But for now this issue is about dockization, flatpack or snap. lets keep to that subject.

**Comment by AbdelrhmanNile** [comment]
@khalilgharbaoui @GarnetSunset 
its available as an appimage now!
https://github.com/AbdelrhmanNile/UnderTaker141

**Comment by ghost** [comment]
Thank you!
