### ISSUE TITLE
Game not found

### ISSUE THREAD

**Issue by mowohre** [AbdelrhmanNile/steal#36]
Everything works as it should, except when i search for Shadow of the Tomb Raider or Tomb raider games in general they don't show up.
Other Games show up when i search for them.

**Comment by AbdelrhmanNile** [comment]
i havent updated the games database in a while. will update it now

**Comment by mowohre** [comment]
Thanx :)

**Comment by AbdelrhmanNile** [comment]
@mowohre 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
