### ISSUE TITLE
Can't install on pop!OS

### ISSUE THREAD

**Issue by colonnezi** [AbdelrhmanNile/steal#37]
chmod +x build.sh && ./build.sh
bash: ./build.sh: /usr/bin/tcsh: interpretador incorreto: Arquivo ou diretório inexistente

**Comment by AbdelrhmanNile** [comment]
install tcsh

**Comment by AbdelrhmanNile** [comment]
`sudo apt-get install csh`

**Comment by colonnezi** [comment]
same error

**Comment by colonnezi** [comment]
Waiting feedback if possible

**Comment by AbdelrhmanNile** [comment]
hi, i believe its because you are trying to execute the script with bash while it is a tcsh script

**Comment by AbdelrhmanNile** [comment]
make sure that you have the tcsh interpreter installed

**Comment by AbdelrhmanNile** [comment]
if you have csh then symlink it to tcsh

**Comment by colonnezi** [comment]
Thanks for the reply! unfortunately, i don't really know what you're talking about. I've installed csh via terminal with the sudo apt-get install csh command.

**Comment by colonnezi** [comment]
Please some help... It's very annoying find p games for linux

**Comment by ArnoldLaynee** [comment]
> Please some help... It's very annoying find p games for linux

`sudo apt-get install tcsh`
try this

**Comment by colonnezi** [comment]
> > Please some help... It's very annoying find p games for linux
> 
> `sudo apt-get install tcsh` try this

```
titot@jarvis-v5-1:~/Área de Trabalho$ cd steal/
titot@jarvis-v5-1:~/Área de Trabalho/steal$ chmod +x build.sh && ./build.sh 
output will be to steal
uuencode: Command not found.
```

**Comment by AbdelrhmanNile** [comment]
@colonnezi 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
