### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by jonathan-realman** [AbdelrhmanNile/steal#38]
I installed it over the Pirate repo 
Here is the Terminal output.
[output.txt](https://github.com/AbdelrhmanNile/steal/files/11186675/output.txt)

**Comment by AbdelrhmanNile** [comment]
did you install `requests` module?

**Comment by AbdelrhmanNile** [comment]
@jonathan-realman 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
