### ISSUE TITLE
it wont open

### ISSUE THREAD

**Issue by Muttqn** [AbdelrhmanNile/steal#39]
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/home/kite/.local/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Mar 10 2023, 16:46:00) 
[GCC 8.4.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 186 symbols loaded
pygame 2.3.0 (SDL 2.0.16, Python 3.6.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: pygame
[INFO   ] [Window      ] Provider: pygame
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/kite/.local/lib/python3.6/site-packages/kivy/core/window/window_pygame.py line 42.Called from /home/kite/.local/lib/python3.6/site-packages/kivy/core/__init__.py line 70 by core_select_lib().
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 20.0.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) HD Graphics 620 (KBL GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/kite/.local/lib/python3.6/site-packages/kivy/core/image/img_pygame.py line 27.Called from /home/kite/.local/lib/python3.6/site-packages/kivy/core/image/__init__.py line 460 by load().
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "main.py", line 557, in <module>
     app.run()
   File "/home/kite/.local/lib/python3.6/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/kite/.local/lib/python3.6/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "main.py", line 510, in build
     self.browse = BrowseTabLayout()
   File "main.py", line 377, in __init__
     self.response = api.search("")
   File "/tmp/steal/steal_db_api.py", line 36, in search
     return data["documents"]
 TypeError: string indices must be integers

**Comment by ghost** [comment]
DBs dead I think

**Comment by ghost** [comment]
Any quick fixes?

**Comment by ghl3m0n** [comment]
![image](https://github.com/AbdelrhmanNile/steal/assets/86513940/94fe3877-2280-4be9-ad55-13cf62a1e5a3)

still not resolved for me, any solutions?

**Comment by AbdelrhmanNile** [comment]
Hi all, i havent maintained it in years, i am thinking of re-writing the whole project very soon

**Comment by ghost** [comment]
Picked up on that myself, might wanna close the issue :) and link the new project when its up!

**Comment by AbdelrhmanNile** [comment]
@GarnetSunset @Muttqn 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
