### ISSUE TITLE
Tracking the status of a title

### ISSUE THREAD

**Issue by Miusaky** [AbdelrhmanNile/steal#4]
Awesome project! Thanks for developing it. A few thoughts:

1. How do you track the status of a torrent / extract / install? Some kind of status bar or page would be a wonderful addition. 
2. Do the torrents stop and auto-resume once Steal is closed / opened?
3. Consider mirroring this repo elsewhere incase Github decide to take it down.

**Comment by AbdelrhmanNile** [comment]
im glad you like it :)
1- as of now you can track everything from the terminal session you opened steal from, ill work on a status bar asap.
2- they stop when it is closed / the terminal is closed, when you open steal again and try to download the game again it will resume
3- ill consider that, thanks!
