### ISSUE TITLE
Unable to install on Archlinux - steam deck

### ISSUE THREAD

**Issue by mox512** [AbdelrhmanNile/steal#43]
paru -S steal-git
results in : 
(130)(deck@MMM yay)$ paru -S steal-git --noconfirm
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Repo (35) blas-3.10.1-1  cblas-3.10.1-1  
    lapack-3.10.1-1  python-numpy-1.23.3-1  
    python-six-1.16.0-6  python-dateutil-2.8.2-4  
    python-pytz-2022.1-1  python-appdirs-1.4.4-7  
    python-more-itertools-8.14.0-1  
    python-jaraco.functools-3.5.2-1  
    python-jaraco.context-4.1.2-1  python-autocommand-2.2.1-1
    cython-0.29.32-2  python-pydantic-1.10.2-1  
    python-inflect-6.0.0-1  python-jaraco.text-3.9.1-1  
    python-ordered-set-4.1.0-1  python-pyparsing-3.0.9-1  
    python-packaging-21.3-1  python-tomli-2.0.1-1  
    python-trove-classifiers-2022.9.26-1  
    python-validate-pyproject-0.10.1-1  
    python-setuptools-1:63.4.2-1  python-pandas-1.4.4-1  
    libuv-1.44.2-1  c-ares-1.18.1-1  nodejs-18.11.0-2  
    nodejs-nopt-6.0.0-1  semver-7.3.8-1  node-gyp-9.2.0-1  
    npm-8.19.2-1  jemalloc-1:5.3.0-1  gflags-2.2.2-4  
    google-glog-0.6.0-1  fmt-9.1.0-1
Aur (5) python-pebble-5.0.3-1  
    webtorrent-cli-4.1.0-1  dwarfs-bin-0.6.2-1  zpaq-7.15-1
    steal-git-r90.736bc20-2

:: Proceed to review? [Y/n]: 

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
resolving dependencies...
looking for conflicting packages...

Packages (35) blas-3.10.1-1  c-ares-1.18.1-1  cblas-3.10.1-1
              cython-0.29.32-2  fmt-9.1.0-1  gflags-2.2.2-4
              google-glog-0.6.0-1  jemalloc-1:5.3.0-1
              lapack-3.10.1-1  libuv-1.44.2-1
              node-gyp-9.2.0-1  nodejs-18.11.0-2
              nodejs-nopt-6.0.0-1  npm-8.19.2-1
              python-appdirs-1.4.4-7
              python-autocommand-2.2.1-1
              python-dateutil-2.8.2-4
              python-inflect-6.0.0-1
              python-jaraco.context-4.1.2-1
              python-jaraco.functools-3.5.2-1
              python-jaraco.text-3.9.1-1
              python-more-itertools-8.14.0-1
              python-numpy-1.23.3-1
              python-ordered-set-4.1.0-1
              python-packaging-21.3-1  python-pandas-1.4.4-1
              python-pydantic-1.10.2-1
              python-pyparsing-3.0.9-1  python-pytz-2022.1-1
              python-setuptools-1:63.4.2-1
              python-six-1.16.0-6  python-tomli-2.0.1-1
              python-trove-classifiers-2022.9.26-1
              python-validate-pyproject-0.10.1-1
              semver-7.3.8-1

Total Download Size:     1.03 MiB
Total Installed Size:  194.82 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 google-glog-0.6....    86.5 KiB   183 KiB/s 00:00 [###] 100%
 gflags-2.2.2-4-x...   148.6 KiB   310 KiB/s 00:00 [###] 100%
 jemalloc-1:5.3.0...   373.1 KiB   636 KiB/s 00:01 [###] 100%
 fmt-9.1.0-1-x86_64    449.2 KiB   518 KiB/s 00:01 [###] 100%
 Total (4/4)          1057.4 KiB   907 KiB/s 00:01 [###] 100%
(35/35) checking keys in keyring                   [###] 100%
(35/35) checking package integrity                 [###] 100%
error: python-jaraco.text: signature from "Chih-Hsuan Yen <yan12125@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/python-jaraco.text-3.9.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.

**Comment by AbdelrhmanNile** [comment]
@mox512 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
