### ISSUE TITLE
Python Error on start

### ISSUE THREAD

**Issue by sphere1001** [AbdelrhmanNile/steal#44]
Hello , I think your application is great, but it is not working for me.
Here is the Error code from Python.

`File "kivy/_event.pyx", line 731, in kivy._event.EventDispatcher.dispatch
   File "/tmp/steal/main.py", line 517, in on_start
     self.browse.add_cards()
   File "/tmp/steal/main.py", line 382, in add_cards
     threading.Thread(target=self.create_cards, name="create_cards").run()
   File "/usr/lib/python3.10/threading.py", line 953, in run
     self._target(*self._args, **self._kwargs)
   File "/tmp/steal/main.py", line 392, in create_cards
     cover_url=game["cover"],
 TypeError: string indices must be integers`

could you try and help ?

**Comment by ghl3m0n** [comment]
I got this error too, any solutions?

**Comment by AbdelrhmanNile** [comment]
hello, i havent maintained this project for so long, i am thinking of re-writing it very soon and make a better version of it

**Comment by AbdelrhmanNile** [comment]
@sphere1001 @ghl3m0n 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141

**Comment by sphere1001** [comment]
Hi there ,
thx for the new link to the game center, but it keeps crashing
with this
raise APIConnectionError(error_message, response=response)
 qbittorrentapi.exceptions.APIConnectionError: Failed to connect to
qBittorrent. Connection Error:
ConnectionError(MaxRetryError("HTTPConnectionPool(host='localhost',
port=8080): Max retries exceeded with url: /api/v2/torrents/info (Caused by
NewConnectionError('<urllib3.connection.HTTPConnection object at
0x7fd10af326d0>: Failed to establish a new connection: [Errno 111]
Connection refused'))"))

Do you probably have any suggestions ?

**Comment by AbdelrhmanNile** [comment]
@sphere1001 
make sure that qbittorent is installed and its webui is enabled on localhost:8080, with username admin and password adminadmin

**Comment by sphere1001** [comment]
Hi there,
it works now like a charm. Just enabled the Web-UI and it runs fine.
Thank you for your help,
kind regards,

Denis.
