### ISSUE TITLE
Native build only option

### ISSUE THREAD

**Issue by HalanoSiblee** [AbdelrhmanNile/steal#46]
**Hello :**

why would steal Depend on ~~wine~~ when it should be an build Option for people who want windows games on linux
for me I only play native linux games no need for wine-staging or xclip (wlroots)
it's gonna mess my system for install wine with lib32 i don't use.

**Comment by AbdelrhmanNile** [comment]
hello
please check out the new application 
https://github.com/AbdelrhmanNile/UnderTaker141
steal is no longer maintained
