### ISSUE TITLE
Dependency issues with aur and arch linux

### ISSUE THREAD

**Issue by bhaswata08** [AbdelrhmanNile/steal#47]
Installed via AUR Using yay

Issue:
Python 3.11.4
Python is installed, but Kivy is also required
Use you package Manager or 'apt-get' to install Kivy

python-kivy is already installed but no dice. 

Steps to recreate:
1. Arch setup with kde installed
2. `yay -S steal-git`
3. launch steal via console

I haven't tried with other distros

**Comment by AbdelrhmanNile** [comment]
@bhaswata08 
hello, this project is deprecated, and been replaced with [UnderTaker141](https://github.com/AbdelrhmanNile/UnderTaker141)
