### ISSUE TITLE
`dwarfs` not available on my distro (Solus)

### ISSUE THREAD

**Issue by Abhinav1217** [AbdelrhmanNile/steal#5]
I have added every other dependencies mentioned on readme file, but I couldn't find dwarfs.

So I looked it up on pkg.org, I found the binaries but couldn't find the actual source code to build my own. If you can point me to a repo, it would be great.

I then downloaded the required libs and binaries, and tried to run it, after solving some linking issues with .so files, I am now stuck with following symbol lookup error,

```
abhinav@abhinav-sol ~/Project/steal/drawfs/usr/share $ dwarfs
dwarfs: symbol lookup error: dwarfs: undefined symbol: _ZN6google15ErrnoLogMessageC1EPKciilMNS_10LogMessageEFvvE
```

1. Can you help me solve this?
2. Steal is launching and I have currently started a game to download ( it will take some time). How necessary is dwarfs? I couldn't find much on google search maybe because of such generic name.

_P.S. I have asked help regarding dwarfs on solus forum also, but I couldn't find a lot about this package. Closest thing I found was dwarfs debugging tool from gnu_

**Comment by AbdelrhmanNile** [comment]
this is dwarfs repo: 
https://github.com/mhx/dwarfs
you can open an issue there, also you can contact johncena141 group on their matrix server (https://matrix.to/#/%23rumpowered:matrix.org), they will help you better
some of their repacks use dwarfs for compression, you will not be able to play them

**Comment by Abhinav1217** [comment]
> this is dwarfs repo: https://github.com/mhx/dwarfs you can open an issue there.

Thanks, I have opened issue there regarding this. 

>  also you can contact johncena141 group on their matrix server (https://matrix.to/#/%23rumpowered:matrix.org)

Thanks for this, I never used matrix, something new to try it out. I didn't even knew about jc141, I only found out about it after you made a reddit post for steal.
