### ISSUE TITLE
Steal in lower resolution monitors doesn't display the full application

### ISSUE THREAD

**Issue by NBZion** [AbdelrhmanNile/steal#7]
when I try to maximize the window, it doesn't show everything in the screen, my monitor's resolution is 1366x768 so i only see a part of the window. 
![image](https://user-images.githubusercontent.com/69440550/175806046-b0588901-9532-467b-b3ee-de84534a9b8c.png)

**Comment by AbdelrhmanNile** [comment]
you can edit the resolution to your desired one by editing main.py line 24 and rebuild steal and install it :)
